spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/hotelaria_db?createDatabaseIfNotExist=true
    username: root
    password: root
  jackson:
    defaultPropertyInclusion: non_null